"""prune streetcleaning table

Revision ID: 374e250aff68
Revises: 4c77fa2ee6ba
Create Date: 2014-10-25 14:34:49.467802

"""

# revision identifiers, used by Alembic.
revision = '374e250aff68'
down_revision = '4c77fa2ee6ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streetCleaning', sa.Column('side', sa.String(length=10), nullable=True))
    op.add_column('streetCleaning', sa.Column('street_max', sa.Integer(), nullable=True))
    op.add_column('streetCleaning', sa.Column('street_min', sa.Integer(), nullable=True))
    op.drop_column('streetCleaning', 'cnnrightle')
    op.drop_column('streetCleaning', 'lf_fadd')
    op.drop_column('streetCleaning', 'rt_fadd')
    op.drop_column('streetCleaning', 'rt_toadd')
    op.drop_column('streetCleaning', 'lf_toadd')
    op.drop_column('streetCleaning', 'corridor')
    op.drop_column('streetCleaning', 'blockside')
    op.drop_column('streetCleaning', 'cnn')
    op.drop_column('streetCleaning', 'blocksweep')
    op.drop_column('streetCleaning', 'nhood')
    op.drop_column('streetCleaning', 'district')
    op.drop_column('streetCleaning', 'zip_code')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streetCleaning', sa.Column('blocksweep', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('streetCleaning', sa.Column('cnn', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('streetCleaning', sa.Column('blockside', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('streetCleaning', sa.Column('corridor', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('streetCleaning', sa.Column('lf_toadd', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('streetCleaning', sa.Column('rt_toadd', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('streetCleaning', sa.Column('rt_fadd', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('streetCleaning', sa.Column('lf_fadd', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('streetCleaning', sa.Column('cnnrightle', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('streetCleaning', sa.Column('nhood', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('streetCleaning', sa.Column('district', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('streetCleaning', sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('streetCleaning', 'street_min')
    op.drop_column('streetCleaning', 'street_max')
    op.drop_column('streetCleaning', 'side')
    ### end Alembic commands ###
