"""create streetCleaning table

Revision ID: 402e6284f373
Revises: None
Create Date: 2014-07-20 21:55:43.447833

"""

# revision identifiers, used by Alembic.
revision = '402e6284f373'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streetCleaning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnn', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.String(length=10), nullable=True),
    sa.Column('blockside', sa.String(length=10), nullable=True),
    sa.Column('blocksweep', sa.String(length=10), nullable=True),
    sa.Column('cnnrightle', sa.String(length=10), nullable=True),
    sa.Column('corridor', sa.String(length=50), nullable=True),
    sa.Column('fromhour', sa.Integer(), nullable=True),
    sa.Column('tohour', sa.Integer(), nullable=True),
    sa.Column('holidays', sa.Boolean(), nullable=True),
    sa.Column('week1ofmon', sa.Boolean(), nullable=True),
    sa.Column('week2ofmon', sa.Boolean(), nullable=True),
    sa.Column('week3ofmon', sa.Boolean(), nullable=True),
    sa.Column('week4ofmon', sa.Boolean(), nullable=True),
    sa.Column('week5ofmon', sa.Boolean(), nullable=True),
    sa.Column('lf_fadd', sa.String(length=10), nullable=True),
    sa.Column('lf_toadd', sa.String(length=10), nullable=True),
    sa.Column('rt_toadd', sa.String(length=10), nullable=True),
    sa.Column('rt_fadd', sa.String(length=10), nullable=True),
    sa.Column('streetname', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('nhood', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streetCleaning')
    ### end Alembic commands ###
