"""location table

Revision ID: 4c77fa2ee6ba
Revises: 402e6284f373
Create Date: 2014-10-03 12:11:46.563592

"""

# revision identifiers, used by Alembic.
revision = '4c77fa2ee6ba'
down_revision = '402e6284f373'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('isCurrent', sa.Boolean(), nullable=True),
    sa.Column('streetNumber', sa.Integer(), nullable=True),
    sa.Column('streetName', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    ### end Alembic commands ###
